#Khối lệnh Try...Catch
try:
    x=5
    y=0
    z=x/y
    print(z)
except:
    print("Bị lỗi rồi bạn ơi!")
print("Cảm ơn bạn đã tính toán giúp tôi")